// components/add/items-data.js
export const ITEMS = [
  // Dairy & Eggs
  "Milk",
  "Whole Milk",
  "Skim Milk",
  "Almond Milk",
  "Oat Milk",
  "Soy Milk",
  "Butter",
  "Unsalted Butter",
  "Margarine",
  "Cream Cheese",
  "Sour Cream",
  "Yogurt",
  "Greek Yogurt",
  "Plain Yogurt",
  "Flavored Yogurt",
  "Eggs",
  "Free-Range Eggs",
  "Egg Whites",

  // Produce
  "Apples",
  "Bananas",
  "Oranges",
  "Strawberries",
  "Blueberries",
  "Raspberries",
  "Grapes",
  "Watermelon",
  "Cantaloupe",
  "Pineapple",
  "Mango",
  "Avocado",
  "Tomatoes",
  "Cherry Tomatoes",
  "Onions",
  "Yellow Onions",
  "Red Onions",
  "Potatoes",
  "Russet Potatoes",
  "Sweet Potatoes",
  "Carrots",
  "Celery",
  "Lettuce",
  "Romaine Lettuce",
  "Spinach",
  "Kale",
  "Cucumber",
  "Bell Peppers",
  "Broccoli",
  "Cauliflower",
  "Mushrooms",
  "Garlic",
  "Ginger",

  // Meat & Seafood
  "Chicken Breast",
  "Chicken Thighs",
  "Ground Chicken",
  "Whole Chicken",
  "Beef",
  "Ground Beef",
  "Steak",
  "Ribeye",
  "Sirloin",
  "Pork Chops",
  "Ground Pork",
  "Bacon",
  "Sausage",
  "Ham",
  "Turkey Breast",
  "Ground Turkey",
  "Salmon",
  "Tilapia",
  "Shrimp",
  "Canned Tuna",
  "Canned Salmon",

  // Bakery & Bread
  "Bread",
  "Whole Wheat Bread",
  "White Bread",
  "Sourdough",
  "Bagels",
  "Croissants",
  "Tortillas",
  "Corn Tortillas",
  "Flour Tortillas",
  "Pita Bread",
  "Buns",
  "Rolls",
  "Muffins",
  "Donuts",
  "Cake",
  "Pie",

  // Pantry
  "Rice",
  "White Rice",
  "Brown Rice",
  "Jasmine Rice",
  "Basmati Rice",
  "Pasta",
  "Spaghetti",
  "Penne",
  "Macaroni",
  "Lasagna Noodles",
  "Flour",
  "All-Purpose Flour",
  "Whole Wheat Flour",
  "Sugar",
  "Brown Sugar",
  "Salt",
  "Sea Salt",
  "Pepper",
  "Black Pepper",
  "Olive Oil",
  "Vegetable Oil",
  "Coconut Oil",
  "Vinegar",
  "Balsamic Vinegar",
  "Soy Sauce",
  "Hot Sauce",
  "Ketchup",
  "Mustard",
  "Mayonnaise",
  "Peanut Butter",
  "Jam",
  "Honey",
  "Cereal",
  "Oatmeal",
  "Granola",
  "Crackers",
  "Popcorn",

  // Canned & Jarred
  "Canned Beans",
  "Black Beans",
  "Kidney Beans",
  "Chickpeas",
  "Canned Corn",
  "Canned Tomatoes",
  "Tomato Sauce",
  "Tomato Paste",
  "Soup",
  "Chicken Broth",
  "Vegetable Broth",
  "Pickles",
  "Olives",
  "Pasta Sauce",

  // Frozen
  "Frozen Vegetables",
  "Frozen Peas",
  "Frozen Corn",
  "Frozen Broccoli",
  "Frozen Fruit",
  "Frozen Berries",
  "Ice Cream",
  "Frozen Pizza",
  "Frozen Meals",

  // Beverages
  "Coffee",
  "Ground Coffee",
  "Coffee Beans",
  "Tea",
  "Green Tea",
  "Herbal Tea",
  "Juice",
  "Orange Juice",
  "Apple Juice",
  "Cranberry Juice",
  "Water",
  "Sparkling Water",
  "Soda",
  "Coke",
  "Pepsi",
  "Sprite",
  "Beer",
  "Wine",
  "Red Wine",
  "White Wine",

  // Snacks
  "Chips",
  "Potato Chips",
  "Tortilla Chips",
  "Pretzels",
  "Nuts",
  "Almonds",
  "Cashews",
  "Peanuts",
  "Trail Mix",
  "Cookies",
  "Chocolate Chip Cookies",
  "Candy",
  "Chocolate Bar",
  "Gum",

  // Household
  "Paper Towels",
  "Toilet Paper",
  "Napkins",
  "Trash Bags",
  "Aluminum Foil",
  "Plastic Wrap",
  "Ziploc Bags",
  "Laundry Detergent",
  "Dish Soap",
  "Sponges",
  "All-Purpose Cleaner",
  "Batteries",
  "Light Bulbs",

  // Personal Care
  "Soap",
  "Hand Soap",
  "Body Wash",
  "Shampoo",
  "Conditioner",
  "Toothpaste",
  "Toothbrush",
  "Deodorant",
  "Razor",
  "Shaving Cream",
  "Facial Cleanser",
  "Lotion",
  "Sunscreen",

  // Baby & Pet
  "Baby Food",
  "Diapers",
  "Baby Wipes",
  "Formula",
  "Dog Food",
  "Cat Food",
  "Pet Treats",
];
